// Generated by CoffeeScript 1.3.3
(function() {
  var Foo, c;

  Foo = (function() {
    var foo;

    function Foo() {}

    foo = function() {
      return "foo";
    };

    Foo.prototype.bar = function() {
      return foo();
    };

    return Foo;

  })();

  c = new Foo;

  console.log("Calling through public api : " + c.bar());
  console.log("Calling through private api, should fail : " + c.foo());

}).call(this);
