// Generated by CoffeeScript 1.3.3
(function() {
  var Boy, sue;

  Boy = function() {};

  Boy.prototype.sing = function() {
    return console.log("It ain't easy being a boy named Sue");
  };

  sue = new Boy();

  sue.sing();

}).call(this);
